import { EvmBatchProcessor} from '@subsquid/evm-processor'

// generated by the evm-typegen tool
// the events object contains typings for all events defined in the ABI
import { events } from './abi/Gravity'

// the registry of Subsquid-maintained public archives
import { lookupArchive } from '@subsquid/archive-registry'

export const GRAVATAR_CONTRACT = '0x2E645469f354BB4F5c8a05B3b30A929361cf77eC'.toLowerCase()

export const processor = new EvmBatchProcessor()
.setDataSource({
// change the alias to run against other EVM networks, e.g.
// lookupArchive('polygon')
